version: "3"
services:
  webserver:
    build: ./
    container_name: alpine_web    
    restart: always
    ports:
      - "8081:80"
    links:
      - mysql
    volumes:
      - ./webapp:/var/www/localhost/htdocs
  mysql:
    image: mysql:5.7
    container_name: alpine_mysql
    restart: always
    ports:
      - "3308:3306"    
    environment:    
      MYSQL_ROOT_PASSWORD: 'root@alpine'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    volumes:
      - ./data:/var/lib/mysql
